/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TraceabilityRouteImport } from './routes/traceability'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPartnerRouteImport } from './routes/_authenticated/partner'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as VerifyBatchIdRouteImport } from './routes/verify.$batchId'
import { Route as AuthenticatedBatchesIndexRouteImport } from './routes/_authenticated/batches.index'
import { Route as AuthenticatedBatchesIdRouteImport } from './routes/_authenticated/batches.$id'
import { Route as AuthenticatedHiveIdRouteImport } from './routes/_authenticated/hive.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceabilityRoute = TraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnerRoute = AuthenticatedPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyBatchIdRoute = VerifyBatchIdRouteImport.update({
  id: '/verify/$batchId',
  path: '/verify/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBatchesIndexRoute =
  AuthenticatedBatchesIndexRouteImport.update({
    id: '/batches/',
    path: '/batches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBatchesIdRoute = AuthenticatedBatchesIdRouteImport.update({
  id: '/batches/$id',
  path: '/batches/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHiveIdRoute = AuthenticatedHiveIdRouteImport.update({
  id: '/hive/$id',
  path: '/hive/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/reset-password': typeof ResetPasswordRoute
  '/traceability': typeof TraceabilityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/verify/$batchId': typeof VerifyBatchIdRoute
  '/verify/': typeof VerifyIndexRoute
  '/batches/$id': typeof AuthenticatedBatchesIdRoute
  '/hive/$id': typeof AuthenticatedHiveIdRoute
  '/batches/': typeof AuthenticatedBatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/reset-password': typeof ResetPasswordRoute
  '/traceability': typeof TraceabilityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/verify/$batchId': typeof VerifyBatchIdRoute
  '/verify': typeof VerifyIndexRoute
  '/batches/$id': typeof AuthenticatedBatchesIdRoute
  '/hive/$id': typeof AuthenticatedHiveIdRoute
  '/batches': typeof AuthenticatedBatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/reset-password': typeof ResetPasswordRoute
  '/traceability': typeof TraceabilityRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/partner': typeof AuthenticatedPartnerRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/verify/$batchId': typeof VerifyBatchIdRoute
  '/verify/': typeof VerifyIndexRoute
  '/_authenticated/batches/$id': typeof AuthenticatedBatchesIdRoute
  '/_authenticated/hive/$id': typeof AuthenticatedHiveIdRoute
  '/_authenticated/batches/': typeof AuthenticatedBatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/explore'
    | '/login'
    | '/platform'
    | '/reset-password'
    | '/traceability'
    | '/admin'
    | '/dashboard'
    | '/partner'
    | '/profile'
    | '/verify/$batchId'
    | '/verify/'
    | '/batches/$id'
    | '/hive/$id'
    | '/batches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/explore'
    | '/login'
    | '/platform'
    | '/reset-password'
    | '/traceability'
    | '/admin'
    | '/dashboard'
    | '/partner'
    | '/profile'
    | '/verify/$batchId'
    | '/verify'
    | '/batches/$id'
    | '/hive/$id'
    | '/batches'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/explore'
    | '/login'
    | '/platform'
    | '/reset-password'
    | '/traceability'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/partner'
    | '/_authenticated/profile'
    | '/verify/$batchId'
    | '/verify/'
    | '/_authenticated/batches/$id'
    | '/_authenticated/hive/$id'
    | '/_authenticated/batches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TraceabilityRoute: typeof TraceabilityRoute
  VerifyBatchIdRoute: typeof VerifyBatchIdRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traceability': {
      id: '/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof TraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$batchId': {
      id: '/verify/$batchId'
      path: '/verify/$batchId'
      fullPath: '/verify/$batchId'
      preLoaderRoute: typeof VerifyBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/batches/': {
      id: '/_authenticated/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof AuthenticatedBatchesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batches/$id': {
      id: '/_authenticated/batches/$id'
      path: '/batches/$id'
      fullPath: '/batches/$id'
      preLoaderRoute: typeof AuthenticatedBatchesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hive/$id': {
      id: '/_authenticated/hive/$id'
      path: '/hive/$id'
      fullPath: '/hive/$id'
      preLoaderRoute: typeof AuthenticatedHiveIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPartnerRoute: typeof AuthenticatedPartnerRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedBatchesIdRoute: typeof AuthenticatedBatchesIdRoute
  AuthenticatedHiveIdRoute: typeof AuthenticatedHiveIdRoute
  AuthenticatedBatchesIndexRoute: typeof AuthenticatedBatchesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPartnerRoute: AuthenticatedPartnerRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedBatchesIdRoute: AuthenticatedBatchesIdRoute,
  AuthenticatedHiveIdRoute: AuthenticatedHiveIdRoute,
  AuthenticatedBatchesIndexRoute: AuthenticatedBatchesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TraceabilityRoute: TraceabilityRoute,
  VerifyBatchIdRoute: VerifyBatchIdRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
